# Generated by Django 3.1.4 on 2023-03-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cusservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusservice',
            new_name='Cus_service',
        ),
    ]
