# Generated by Django 3.1.4 on 2023-04-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
