# Generated by Django 3.1.4 on 2023-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='mode',
            field=models.CharField(choices=[('debit', 'debit'), ('paypal', 'paypal'), ('cod', 'cod'), ('credit', 'credit')], default='cod', max_length=20),
        ),
    ]
